FlareZone/FlareZone

index.html
src/components/part/landing.tsx

fix: layout view logo

---

src/components/part/landing.tsx
src/styles/landing-style.module.css

Liwei_landing_fix1

---

index.html
src/styles/landing-style.module.css

In order to make the web responsive, I set the maximum width for the Phone type as 400px, except for the iPhone XR(414px width) I test, it works well for other types of phones. If you want to change the max width, please also change the number from 400 to your desired one in the index.html.

landing_fix2

---

src/components/part/hotTopicsStack.tsx
src/components/part/popularAuthorStack.tsx
src/components/part/popularAuthors.tsx
src/components/part/trendingArticleBox.tsx
src/components/part/trendingArticleStack.tsx
src/components/part/trendingHotTopics.tsx
src/components/part/trendingNav.tsx
src/components/part/trendingPageContainer.tsx
src/pages/explore/index.tsx

added trending page

---

src/components/part/accountPageContainer.tsx
src/components/part/followingMillStack.tsx
src/components/part/millPageContainer.tsx
src/pages/explore/account.tsx
src/pages/explore/mill.tsx
src/routes.tsx

init commit

---

src/components/part/sidebar.tsx

feat: add setting show

---

src/components/part/sidebar.tsx

Feat settings

---

src/components/part/sidebar.tsx

fix: rename help email address

---

package.json
pnpm-lock.yaml
src/components/part/sidebar.tsx
src/pages/post/index.tsx
src/routes.tsx

style: repeace style

---

components.json
package.json
pnpm-lock.yaml
src/components/layouts/RootLayout.tsx
src/components/part/sidebar.tsx
src/components/ui/alert.tsx
src/components/ui/toast.tsx
src/components/ui/toaster.tsx
src/components/ui/use-toast.ts
src/pages/account/index.tsx
src/pages/explore/index.tsx
src/pages/mill/index.tsx
tailwind.config.js

fix: FIXME 页面跳转, 有loading, 希望不要loading.

---

src/components/part/accountHeader.tsx
src/components/part/accountPageContainer.tsx
src/components/part/articleBox.tsx
src/components/part/articleBoxWithImgBg.tsx
src/components/part/articleStack.tsx
src/components/part/followingMill.tsx
src/components/part/searchbar.tsx
src/components/part/trendingNav.tsx
src/pages/wallet/index.tsx
src/routes.tsx

style: use unocss to replace css

---

src/components/part/trendingNav.tsx
src/components/part/trendingUserBox.tsx
src/components/part/trendingUserStack.tsx

added users on trending page

---

package.json
pnpm-lock.yaml
src/components/part/Follow.ts
src/components/part/accountHeader.tsx
src/type.ts

feat: use swr to get data and render account header

---

src/components/ui/table.tsx
src/pages/wallet/index.tsx
src/state/tx.ts
src/type.ts

feat: add wallet detail

---

src/components/part/postPagePublishedBox.tsx

Fixing issues in postPagePublishedBox

---

src/components/part/sidebar.tsx
src/pages/wallet/index.tsx

feat: 查看wallet 必须 connect wallet

---

package.json
pnpm-lock.yaml
src/components/part/articleBox.tsx
src/components/part/sidebar.tsx
src/pages/wallet/index.tsx

Fix wallet show

---

src/components/part/postPageContainer.tsx
src/components/part/sidebar.tsx

feat: new post must connect wallet

---

src/components/part/postPageContainer.tsx
src/components/part/postPageEditor.tsx
src/components/part/postPageHeader.tsx
src/components/part/postPageNav.tsx

Redesigned the header of Post page and refactored some codes.
Some features on the editor are still not done yet.

Feat post page redesign

---

package.json
pnpm-lock.yaml
src/components/part/accountPageContainer.tsx
src/components/part/articleBox.tsx
src/components/part/articleStack.tsx

style: account-show

---

src/components/part/accountPageContainer.tsx
src/components/part/followingMill.tsx
src/components/part/followingMillStack.tsx

style: update Following Mills style

---

package.json
pnpm-lock.yaml
src/components/part/searchbar.tsx
src/main.tsx

https://github.com/FlareZone/FlareZone/issues/57

feat: add Notifications but not show

---

package.json
pnpm-lock.yaml
src/lib/utils.ts
src/pages/wallet/index.tsx
src/type.ts

style: update wallet style

---

src/components/part/account/accountPageContainer.tsx
src/components/part/mill/millPageContainer.tsx
src/components/part/searchbar.tsx
src/components/part/sidebar.tsx

style: some style

---

src/components/part/account/accountHeader.tsx
src/components/part/account/accountPageContainer.tsx
src/components/part/articleCard/articleStack.tsx
src/pages/404/index.tsx
src/routes.tsx

add 404 page and user not exist page

feat: add 404 page and user not exist page

---

src/components/part/account/accountPageContainer.tsx

fix: add loading in account page fix user not fount page

---

src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx
src/main.tsx
src/pages/status/index.tsx
src/routes.tsx
src/state/Status.ts
src/styles/common.css

add note detail.
http://localhost:5173/@song/status/30-264

Feat note detail

---

src/components/part/trending/trendingHotTopics.tsx
src/components/part/trending/trendingNav.tsx
src/state/HotTopics.ts
src/type.ts

use data to render hot topics.

feat: use data to render hot topics

---

src/components/part/trending/trendingUserBox.tsx
src/components/part/trending/trendingUserStack.tsx
src/state/TrendingUser.ts

add user show but no use.
FIXME

feat: trending user show

---

package.json
pnpm-lock.yaml
src/components/part/trending/trendingUserBox.tsx
src/components/part/trending/trendingUserStack.tsx

feat: add trending user

---

package.json
pnpm-lock.yaml
src/components/part/articleCard/articleBox.tsx
src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingArticleStack.tsx
src/pages/status/index.tsx
src/share/ipfs/index.ts
src/state/Character.ts

Feat most popular

---

index.html
src/components/part/landing.tsx
src/styles/landing-style.module.css

Landing page refix1

---

src/components/part/articleCard/articleBox.tsx
src/components/part/post/postPageHeader.tsx

feat: use do gambling with post

---

src/components/part/articleCard/articleBox.tsx
src/components/part/post/postPageHeader.tsx
src/vite-env.d.ts

fix: can't show in mobile

---

src/components/part/landing.tsx

style(src): fix > to &gt;

---

package.json
pnpm-lock.yaml
src/main.tsx
src/pages/sign-in/index.tsx
src/pages/sign-up/index.tsx
src/routes.tsx

feat: add rl

---

.github/changelog.yml

chore(.github) add changelog

---

src/components/part/landing.tsx

style(part/landing.tsx) replace click link

---

package.json
pnpm-lock.yaml
src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingArticleStack.tsx

Feat trending to refresh

---

src/components/layouts/RootLayout.tsx
src/components/part/post/postPageHeader.tsx
src/components/ui/colorModeSwitch.tsx
src/pages/post/index.tsx
src/themes/theme.ts

feat: add darkmode to post

---

src/components/part/status/index.tsx
src/components/part/trending/trendingArticleBox.tsx
src/pages/status/index.tsx
src/state/Account.ts

styl(part/status): page show

---

src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx
src/components/part/trending/popularAuthors.tsx
src/components/part/trending/trendingArticleBox.tsx

fix(src): detail some show code Issue #102

---

src/components/part/trending/trendingUserBox.tsx
src/components/part/trending/trendingUserStack.tsx

Refactor and fix spacing in trending user box

---

src/components/part/trending/trendingArticleBox.tsx

added a template button for scroll to top on trending page

---

src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx

点击 account 页面的帖子，跳转到 status 页面的帖子.

feat(account): click account note to status

---

src/components/part/trending/trendingArticleBox.tsx

Trending pg scroll up

---

src/components/part/trending/popularAuthors.tsx

feat(trending): popular loading too low

---

src/components/part/account/accountPageContainer.tsx
src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx
src/components/part/articleCard/articleTag.tsx

feat(account): detail show

---

src/components/part/account/accountPageContainer.tsx
src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx
src/components/part/articleCard/articleTag.tsx

Feat account skeleton

---

src/components/layouts/RootLayout.tsx
src/components/part/appearance-switch.tsx
src/components/part/sidebar.tsx
src/components/part/trending/hotTopicsStack.tsx
src/components/part/trending/popularAuthorStack.tsx
src/components/part/trending/trendingNav.tsx
src/themes/theme.ts

Added Full page dark mode

---

src/themes/theme.ts

fix(theme): use 	initialColorMode: "light"

---

src/components/part/articleCard/articleBoxWithImgBg.tsx
src/components/part/mill/millPageContainer.tsx
src/components/part/trending/hotTopicsStack.tsx
src/components/part/trending/popularAuthorStack.tsx
src/components/part/trending/popularAuthors.tsx
src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingNav.tsx
src/components/part/trending/trendingPageContainer.tsx
src/hooks/useDark.ts
src/state/HotTopics.ts
src/state/TrendingUser.ts
src/themes/theme.ts
src/type.ts

- detail Popular Authors fetch request use swr to do the request.
- style: update mill show and add phone style show
- fix trending show scroll bar

Fix popular authors

---

src/lib/utils.ts
src/pages/wallet/index.tsx

style: add skeleton to wallet

---

src/components/part/trending/popularAuthors.tsx
src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingArticleStack.tsx
src/components/part/trending/trendingHotTopics.tsx
src/components/part/trending/trendingUserBox.tsx
src/components/part/trending/trendingUserStack.tsx
src/state/TrendingNote.ts
src/type.ts

feat: use swr to get trending data

---

src/components/part/articleCard/articleBox.tsx
src/components/part/post/postPageHeader.tsx
src/components/part/status/index.tsx
src/components/part/trending/hotTopicsStack.tsx
src/components/part/trending/trendingHotTopics.tsx
src/components/part/trending/trendingNav.tsx
src/components/part/trending/trendingUserBox.tsx

Feat skeleton trending

---

package.json
pnpm-lock.yaml
src/components/part/trending/hotTopicsStack.tsx
src/components/part/trending/popularAuthorStack.tsx
src/components/part/trending/trendingNav.tsx

style: change trending icon

---

src/components/part/account/accountPageContainer.tsx
src/components/part/articleCard/articleBox.tsx
src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingNav.tsx

add toast to share and add skeleton to trending home

style: add toast to share and add skeleton to trending home

---

src/components/part/articleCard/articleBox.tsx
src/components/part/post/postPageEditor.tsx
src/components/part/post/postPageHeader.tsx
src/components/part/status/index.tsx
src/hooks/useUploadFile.ts
src/type.ts

Feat post to chain

---

src/components/part/articleCard/articleBox.tsx
src/components/part/status/index.tsx
src/components/part/trending/trendingArticleBox.tsx
src/state/CommitCount.ts
src/state/CommitInfo.ts
src/type.ts

Rebase commmit

---

src/components/part/account/accountPageContainer.tsx
src/components/part/articleCard/articleBox.tsx
src/components/part/articleCard/articleStack.tsx

fix: use ref account page have double render

---

src/components/part/trending/trendingArticleBox.tsx
src/components/part/trending/trendingNav.tsx

fix: Delete redundant topics
